In [ ]:
import torch
import torch.nn.functional as F
from torch import nn
 
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [46]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [47]:
net = nn.Sequential(nn.Linear(8,128), CenteredLayer())

In [49]:
Y = net(torch.rand(4,8))
Y.mean()

tensor(3.7253e-09, grad_fn=<MeanBackward0>)

In [50]:
class MyLinear(nn.Module):
    def __init__ (self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [51]:
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 1.4571, -0.6042,  1.0103],
        [-0.5093, -1.7012, -2.0499],
        [-0.4167, -0.9743, -1.8456],
        [ 1.2204,  0.9862, -0.8719],
        [-0.4265,  0.8248,  0.5809]], requires_grad=True)

In [52]:
linear(torch.rand(2,5))

tensor([[1.9566, 0.0000, 0.0000],
        [1.4932, 0.0000, 0.0000]])

In [53]:
net = nn.Sequential(MyLinear(64,8), MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.],
        [0.]])