In [63]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [67]:
torch.cuda.device_count()

1

In [65]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [68]:
import torch
print("CUDA 可用:", torch.cuda.is_available())
print("CUDA 设备数量:", torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(i, torch.cuda.get_device_name(i))

CUDA 可用: True
CUDA 设备数量: 1
0 NVIDIA GeForce RTX 4060 Laptop GPU


In [69]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [73]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [85]:
Y = torch.rand(2, 3, device=try_gpu(0))
Y

tensor([[0.0352, 0.3734, 0.2180],
        [0.7253, 0.7977, 0.6416]], device='cuda:0')

In [75]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [86]:
# 要保证都在同一个gpu上
Y + Z

tensor([[1.0352, 1.3734, 1.2180],
        [1.7253, 1.7977, 1.6416]], device='cuda:0')

In [82]:
Z.cuda(0) is Z

True

In [87]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [88]:
net(X)

tensor([[-1.1609],
        [-1.1609]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [89]:
net[0].weight.data.device

device(type='cuda', index=0)